# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:21

stages:
  - test
  - deploy

test:inventory:
  stage: test
  script:
    - yarn global add gulp-cli
    - yarn install
    - yarn run build
  only:
    - merge_requests
  except:
    - master

test:doc:
  image: ruby:3.2
  stage: test
  script:
    - cd documentation
    - bundle install
    - bundle exec jekyll build
  only:
    - merge_requests
  except:
    - master

test:data:
  stage: test
  script:
    - yarn install
    # gulp-jest won't work until https://github.com/Nerajno/gulp-jest/issues/77 is fixed
    # jest-cli to the rescue
    - yarn global add jest-cli
    - yarn run test
  only:
    - merge_requests
  except:
    - master

pages:inventory:
  stage: deploy
  needs: ["pages:docs"]
  script:
    - yarn config set unsafe-perm true
    - yarn global --ignore-optional add gulp-cli netlify-cli
    - yarn install # inventory dependencies
    - yarn run build # build the inventory
    - cp -rT build/ public/ # copying the inventory
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod --dir public/
  artifacts:
    paths:
      - public
  only:
    - master

pages:docs:
  stage: deploy
  image: ruby:3.2
  script:
    - mkdir -p public/docs
    - cd documentation
    - bundle install # documentation dependencies
    - bundle exec jekyll build # build the documentation
    - cp -rT _site/ ../public/docs # copying the documentation
    - cd ..
  artifacts:
    paths:
      - public
  only:
    - master
